// Generated by `supabase gen types typescript` (via Supabase MCP).
// Regenerate after schema changes: see scripts/db-types.sh (TODO).
//
// Trimmed to only the obl_* tables, enums, and functions that this app uses.
// Other tables (chat_*, quinn_*, partner_profiles, rate_stacks, etc.) live in
// the same shared Supabase project but are owned by other apps.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.1";
  };
  public: {
    Tables: {
      obl_alerts: {
        Row: {
          acknowledged: boolean;
          acknowledged_at: string | null;
          acknowledged_by: string | null;
          at: string;
          detail: string | null;
          id: string;
          severity: Database["public"]["Enums"]["obl_severity"];
          tenant_id: string | null;
          title: string;
        };
        Insert: {
          acknowledged?: boolean;
          acknowledged_at?: string | null;
          acknowledged_by?: string | null;
          at?: string;
          detail?: string | null;
          id?: string;
          severity: Database["public"]["Enums"]["obl_severity"];
          tenant_id?: string | null;
          title: string;
        };
        Update: {
          acknowledged?: boolean;
          acknowledged_at?: string | null;
          acknowledged_by?: string | null;
          at?: string;
          detail?: string | null;
          id?: string;
          severity?: Database["public"]["Enums"]["obl_severity"];
          tenant_id?: string | null;
          title?: string;
        };
        Relationships: [];
      };
      obl_audit_entries: {
        Row: {
          action: string;
          actor: string;
          at: string;
          id: string;
          severity: Database["public"]["Enums"]["obl_severity"];
          summary: string;
          tenant_id: string | null;
        };
        Insert: {
          action: string;
          actor: string;
          at?: string;
          id?: string;
          severity?: Database["public"]["Enums"]["obl_severity"];
          summary: string;
          tenant_id?: string | null;
        };
        Update: {
          action?: string;
          actor?: string;
          at?: string;
          id?: string;
          severity?: Database["public"]["Enums"]["obl_severity"];
          summary?: string;
          tenant_id?: string | null;
        };
        Relationships: [];
      };
      obl_connection_health_checks: {
        Row: {
          checked_at: string;
          connection_id: string;
          detail: Json | null;
          id: number;
          latency_ms: number | null;
          status: Database["public"]["Enums"]["obl_connection_status"];
        };
        Insert: {
          checked_at?: string;
          connection_id: string;
          detail?: Json | null;
          id?: number;
          latency_ms?: number | null;
          status: Database["public"]["Enums"]["obl_connection_status"];
        };
        Update: {
          checked_at?: string;
          connection_id?: string;
          detail?: Json | null;
          id?: number;
          latency_ms?: number | null;
          status?: Database["public"]["Enums"]["obl_connection_status"];
        };
        Relationships: [];
      };
      obl_connections: {
        Row: {
          account: string | null;
          config: Json | null;
          connected_at: string | null;
          env: Database["public"]["Enums"]["obl_env"];
          id: string;
          service: Database["public"]["Enums"]["obl_connection_service"];
          tenant_id: string;
        };
        Insert: {
          account?: string | null;
          config?: Json | null;
          connected_at?: string | null;
          env: Database["public"]["Enums"]["obl_env"];
          id?: string;
          service: Database["public"]["Enums"]["obl_connection_service"];
          tenant_id: string;
        };
        Update: {
          account?: string | null;
          config?: Json | null;
          connected_at?: string | null;
          env?: Database["public"]["Enums"]["obl_env"];
          id?: string;
          service?: Database["public"]["Enums"]["obl_connection_service"];
          tenant_id?: string;
        };
        Relationships: [];
      };
      obl_policies: {
        Row: {
          blocked_24h: number;
          description: string | null;
          enforced: boolean;
          id: string;
          name: string;
          updated_at: string;
        };
        Insert: {
          blocked_24h?: number;
          description?: string | null;
          enforced?: boolean;
          id: string;
          name: string;
          updated_at?: string;
        };
        Update: {
          blocked_24h?: number;
          description?: string | null;
          enforced?: boolean;
          id?: string;
          name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      obl_policy_layers: {
        Row: {
          id: number;
          idx: number;
          name: string;
          ok: boolean;
          policy_id: string;
        };
        Insert: {
          id?: number;
          idx: number;
          name: string;
          ok?: boolean;
          policy_id: string;
        };
        Update: {
          id?: number;
          idx?: number;
          name?: string;
          ok?: boolean;
          policy_id?: string;
        };
        Relationships: [];
      };
      obl_profiles: {
        Row: {
          email: string | null;
          id: string;
          invited_at: string | null;
          last_seen: string | null;
          name: string | null;
          platform_role: Database["public"]["Enums"]["obl_platform_role"] | null;
          tenant_id: string | null;
          tenant_role: Database["public"]["Enums"]["obl_tenant_role"] | null;
        };
        Insert: {
          email?: string | null;
          id: string;
          invited_at?: string | null;
          last_seen?: string | null;
          name?: string | null;
          platform_role?: Database["public"]["Enums"]["obl_platform_role"] | null;
          tenant_id?: string | null;
          tenant_role?: Database["public"]["Enums"]["obl_tenant_role"] | null;
        };
        Update: {
          email?: string | null;
          id?: string;
          invited_at?: string | null;
          last_seen?: string | null;
          name?: string | null;
          platform_role?: Database["public"]["Enums"]["obl_platform_role"] | null;
          tenant_id?: string | null;
          tenant_role?: Database["public"]["Enums"]["obl_tenant_role"] | null;
        };
        Relationships: [];
      };
      obl_run_steps: {
        Row: {
          duration_ms: number;
          id: number;
          idx: number;
          payload: Json | null;
          run_id: string;
          status: Database["public"]["Enums"]["obl_step_status"];
          step_id: string;
        };
        Insert: {
          duration_ms?: number;
          id?: number;
          idx: number;
          payload?: Json | null;
          run_id: string;
          status: Database["public"]["Enums"]["obl_step_status"];
          step_id: string;
        };
        Update: {
          duration_ms?: number;
          id?: number;
          idx?: number;
          payload?: Json | null;
          run_id?: string;
          status?: Database["public"]["Enums"]["obl_step_status"];
          step_id?: string;
        };
        Relationships: [];
      };
      obl_runs: {
        Row: {
          duration_ms: number | null;
          error_msg: string | null;
          id: string;
          loan_ref: string | null;
          started_at: string;
          status: Database["public"]["Enums"]["obl_run_status"];
          tenant_id: string;
          workflow_id: string;
        };
        Insert: {
          duration_ms?: number | null;
          error_msg?: string | null;
          id?: string;
          loan_ref?: string | null;
          started_at?: string;
          status: Database["public"]["Enums"]["obl_run_status"];
          tenant_id: string;
          workflow_id: string;
        };
        Update: {
          duration_ms?: number | null;
          error_msg?: string | null;
          id?: string;
          loan_ref?: string | null;
          started_at?: string;
          status?: Database["public"]["Enums"]["obl_run_status"];
          tenant_id?: string;
          workflow_id?: string;
        };
        Relationships: [];
      };
      obl_tenants: {
        Row: {
          created_at: string;
          env: Database["public"]["Enums"]["obl_env"];
          id: string;
          monthly_run_budget: number;
          monthly_runs_used: number;
          name: string;
          plan: Database["public"]["Enums"]["obl_tenant_plan"];
          primary_contact: string | null;
          slug: string;
          status: Database["public"]["Enums"]["obl_tenant_status"];
        };
        Insert: {
          created_at?: string;
          env?: Database["public"]["Enums"]["obl_env"];
          id?: string;
          monthly_run_budget?: number;
          monthly_runs_used?: number;
          name: string;
          plan?: Database["public"]["Enums"]["obl_tenant_plan"];
          primary_contact?: string | null;
          slug: string;
          status?: Database["public"]["Enums"]["obl_tenant_status"];
        };
        Update: {
          created_at?: string;
          env?: Database["public"]["Enums"]["obl_env"];
          id?: string;
          monthly_run_budget?: number;
          monthly_runs_used?: number;
          name?: string;
          plan?: Database["public"]["Enums"]["obl_tenant_plan"];
          primary_contact?: string | null;
          slug?: string;
          status?: Database["public"]["Enums"]["obl_tenant_status"];
        };
        Relationships: [];
      };
      obl_workflows: {
        Row: {
          created_at: string;
          created_by: string | null;
          definition: Json;
          description: string | null;
          env: Database["public"]["Enums"]["obl_env"];
          id: string;
          last_run_at: string | null;
          name: string;
          runs_total: number;
          slug: string;
          status: Database["public"]["Enums"]["obl_workflow_status"];
          success_rate: number;
          tenant_id: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          definition?: Json;
          description?: string | null;
          env?: Database["public"]["Enums"]["obl_env"];
          id?: string;
          last_run_at?: string | null;
          name: string;
          runs_total?: number;
          slug: string;
          status?: Database["public"]["Enums"]["obl_workflow_status"];
          success_rate?: number;
          tenant_id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          definition?: Json;
          description?: string | null;
          env?: Database["public"]["Enums"]["obl_env"];
          id?: string;
          last_run_at?: string | null;
          name?: string;
          runs_total?: number;
          slug?: string;
          status?: Database["public"]["Enums"]["obl_workflow_status"];
          success_rate?: number;
          tenant_id?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      obl_current_tenant_id: { Args: Record<string, never>; Returns: string };
      obl_is_platform_admin: { Args: Record<string, never>; Returns: boolean };
    };
    Enums: {
      obl_connection_service: "encompass" | "anthropic" | "slack" | "email";
      obl_connection_status: "ok" | "degraded" | "down" | "not_connected";
      obl_env: "sandbox" | "production";
      obl_platform_role: "admin" | "support";
      obl_run_status: "succeeded" | "failed" | "running" | "awaiting_human";
      obl_severity: "info" | "warning" | "critical" | "blocked";
      obl_step_status: "ok" | "fail" | "skip";
      obl_tenant_plan: "starter" | "growth" | "enterprise";
      obl_tenant_role: "owner" | "admin" | "operator" | "viewer";
      obl_tenant_status: "active" | "trial" | "suspended";
      obl_workflow_status: "draft" | "live" | "paused" | "error";
    };
    CompositeTypes: Record<string, never>;
  };
};

// Convenience row aliases.
export type DbRow<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type Tenant = DbRow<"obl_tenants">;
export type Profile = DbRow<"obl_profiles">;
export type Workflow = DbRow<"obl_workflows">;
export type Run = DbRow<"obl_runs">;
export type RunStep = DbRow<"obl_run_steps">;
export type ConnectionRow = DbRow<"obl_connections">;
export type ConnectionHealthCheck = DbRow<"obl_connection_health_checks">;
export type AuditEntry = DbRow<"obl_audit_entries">;
export type Alert = DbRow<"obl_alerts">;
export type Policy = DbRow<"obl_policies">;
export type PolicyLayer = DbRow<"obl_policy_layers">;
