import type {
  Tenant,
  PlatformUser,
  AuditEntry,
  PlatformAlert,
  PolicyStatus,
  ConnectionHealth,
  PlatformWorkflow,
} from "./platform-types";

export const SAMPLE_TENANTS: Tenant[] = [
  {
    id: "tnt_acme",
    name: "Acme Lending",
    slug: "acme-lending",
    plan: "enterprise",
    status: "active",
    env: "production",
    createdAt: "2026-01-15T09:00:00Z",
    primaryContact: "ops@acmelending.com",
    workflowsLive: 7,
    runs24h: 2418,
    successRate: 0.96,
    monthlyRunBudget: 100000,
    monthlyRunsUsed: 64320,
  },
  {
    id: "tnt_summit",
    name: "Summit Mortgage",
    slug: "summit-mortgage",
    plan: "growth",
    status: "active",
    env: "production",
    createdAt: "2026-02-04T14:00:00Z",
    primaryContact: "tech@summitmortgage.com",
    workflowsLive: 4,
    runs24h: 612,
    successRate: 0.93,
    monthlyRunBudget: 25000,
    monthlyRunsUsed: 18402,
  },
  {
    id: "tnt_northstar",
    name: "Northstar Home Loans",
    slug: "northstar",
    plan: "growth",
    status: "active",
    env: "production",
    createdAt: "2026-02-20T11:00:00Z",
    primaryContact: "noc@northstar.com",
    workflowsLive: 3,
    runs24h: 188,
    successRate: 0.89,
    monthlyRunBudget: 25000,
    monthlyRunsUsed: 6210,
  },
  {
    id: "tnt_bridgeway",
    name: "Bridgeway Capital",
    slug: "bridgeway",
    plan: "starter",
    status: "trial",
    env: "sandbox",
    createdAt: "2026-04-28T16:00:00Z",
    primaryContact: "engineering@bridgeway.com",
    workflowsLive: 1,
    runs24h: 14,
    successRate: 0.78,
    monthlyRunBudget: 1000,
    monthlyRunsUsed: 312,
  },
  {
    id: "tnt_meridian",
    name: "Meridian Funding",
    slug: "meridian",
    plan: "growth",
    status: "suspended",
    env: "production",
    createdAt: "2025-11-08T09:00:00Z",
    primaryContact: "finance@meridianfunding.com",
    workflowsLive: 0,
    runs24h: 0,
    successRate: 0,
    monthlyRunBudget: 25000,
    monthlyRunsUsed: 0,
  },
];

export const SAMPLE_PLATFORM_USERS: PlatformUser[] = [
  {
    id: "usr_jane",
    email: "jane.morris@acmelending.com",
    name: "Jane Morris",
    tenantId: "tnt_acme",
    tenantName: "Acme Lending",
    role: "owner",
    lastSeen: "2026-05-13T11:42:00Z",
    invitedAt: "2026-01-15T09:00:00Z",
  },
  {
    id: "usr_dan",
    email: "dan.park@acmelending.com",
    name: "Dan Park",
    tenantId: "tnt_acme",
    tenantName: "Acme Lending",
    role: "operator",
    lastSeen: "2026-05-13T10:18:00Z",
    invitedAt: "2026-01-18T09:00:00Z",
  },
  {
    id: "usr_taylor",
    email: "taylor.kim@summitmortgage.com",
    name: "Taylor Kim",
    tenantId: "tnt_summit",
    tenantName: "Summit Mortgage",
    role: "owner",
    lastSeen: "2026-05-12T17:04:00Z",
    invitedAt: "2026-02-04T14:00:00Z",
  },
  {
    id: "usr_marco",
    email: "marco.silva@northstar.com",
    name: "Marco Silva",
    tenantId: "tnt_northstar",
    tenantName: "Northstar Home Loans",
    role: "admin",
    lastSeen: "2026-05-13T09:50:00Z",
    invitedAt: "2026-02-22T11:00:00Z",
  },
  {
    id: "usr_amelia",
    email: "amelia.chen@bridgeway.com",
    name: "Amelia Chen",
    tenantId: "tnt_bridgeway",
    tenantName: "Bridgeway Capital",
    role: "owner",
    lastSeen: "2026-05-13T08:00:00Z",
    invitedAt: "2026-04-28T16:00:00Z",
  },
  {
    id: "usr_grant",
    email: "grant.murphy@bridgeway.com",
    name: "Grant Murphy",
    tenantId: "tnt_bridgeway",
    tenantName: "Bridgeway Capital",
    role: "viewer",
    lastSeen: null,
    invitedAt: "2026-05-10T12:00:00Z",
  },
];

export const SAMPLE_AUDIT: AuditEntry[] = [
  {
    id: "aud_1001",
    at: "2026-05-13T11:30:00Z",
    actor: "platform@openbroker.dev",
    tenantId: "tnt_bridgeway",
    tenantName: "Bridgeway Capital",
    action: "user.invited",
    summary: "Invited grant.murphy@bridgeway.com as viewer",
    severity: "info",
  },
  {
    id: "aud_1000",
    at: "2026-05-13T10:18:00Z",
    actor: "dan.park@acmelending.com",
    tenantId: "tnt_acme",
    tenantName: "Acme Lending",
    action: "workflow.published",
    summary: "Published 'Condition extraction from disclosed docs' v7",
    severity: "info",
  },
  {
    id: "aud_0999",
    at: "2026-05-13T09:14:00Z",
    actor: "runtime",
    tenantId: "tnt_summit",
    tenantName: "Summit Mortgage",
    action: "policy.no_deletion.blocked",
    summary: "Blocked DELETE /encompass/v3/loans/{id} from workflow 'cleanup-pilot'",
    severity: "blocked",
  },
  {
    id: "aud_0998",
    at: "2026-05-13T08:00:00Z",
    actor: "platform@openbroker.dev",
    tenantId: "tnt_meridian",
    tenantName: "Meridian Funding",
    action: "tenant.suspended",
    summary: "Suspended for non-payment; workflows paused",
    severity: "warning",
  },
  {
    id: "aud_0997",
    at: "2026-05-13T07:42:00Z",
    actor: "jane.morris@acmelending.com",
    tenantId: "tnt_acme",
    tenantName: "Acme Lending",
    action: "connection.test",
    summary: "Re-tested Encompass production connection → OK (latency 412ms)",
    severity: "info",
  },
  {
    id: "aud_0996",
    at: "2026-05-12T22:09:00Z",
    actor: "platform@openbroker.dev",
    tenantId: "tnt_acme",
    tenantName: "Acme Lending",
    action: "tenant.plan_changed",
    summary: "Plan changed from growth → enterprise",
    severity: "info",
  },
  {
    id: "aud_0995",
    at: "2026-05-12T18:30:00Z",
    actor: "taylor.kim@summitmortgage.com",
    tenantId: "tnt_summit",
    tenantName: "Summit Mortgage",
    action: "workflow.paused",
    summary: "Paused 'Service SLA babysitter' for parameter review",
    severity: "info",
  },
];

export const SAMPLE_ALERTS: PlatformAlert[] = [
  {
    id: "alr_1",
    severity: "critical",
    tenantId: "tnt_acme",
    title: "Encompass OAuth latency spike",
    detail: "p95 latency exceeded 2.0s in the last 10 minutes on Acme Lending's production environment.",
    at: "2026-05-13T11:35:00Z",
    acknowledged: false,
  },
  {
    id: "alr_2",
    severity: "warning",
    tenantId: "tnt_northstar",
    title: "Trial usage at 82% of monthly budget",
    detail: "Northstar Home Loans burned through 6,210 of 25,000 runs with 18 days left in the cycle.",
    at: "2026-05-13T09:00:00Z",
    acknowledged: false,
  },
  {
    id: "alr_3",
    severity: "info",
    tenantId: null,
    title: "Anthropic API: scheduled maintenance",
    detail: "Anthropic is performing maintenance 2026-05-15 02:00–04:00 UTC. No expected impact.",
    at: "2026-05-12T16:00:00Z",
    acknowledged: true,
  },
];

export const SAMPLE_POLICIES: PolicyStatus[] = [
  {
    id: "no-deletion",
    name: "No-deletion guardrail",
    enforced: true,
    layers: [
      { name: "Catalog filter", ok: true },
      { name: "Portal preflight", ok: true },
      { name: "Runtime HTTP adapter", ok: true },
      { name: "AI tool whitelist", ok: true },
    ],
    blocked24h: 3,
    description:
      "Never delete loans, documents, attachments, conditions, milestones, contacts, or fields in Encompass.",
  },
  {
    id: "sandbox-by-default",
    name: "Sandbox-by-default",
    enforced: true,
    layers: [
      { name: "Trial tenants → sandbox env", ok: true },
      { name: "First-publish warning", ok: true },
    ],
    blocked24h: 0,
    description: "New tenants and new workflows default to the Encompass sandbox until production is explicitly chosen.",
  },
  {
    id: "human-approval-on-write",
    name: "Human approval on writes",
    enforced: false,
    layers: [
      { name: "Catalog hint", ok: true },
      { name: "Required approval step", ok: false },
    ],
    blocked24h: 0,
    description:
      "Recommended pattern: every workflow that writes to Encompass should include a human approval step.",
  },
];

export const SAMPLE_CONNECTION_HEALTH: ConnectionHealth[] = [
  {
    tenantId: "tnt_acme",
    tenantName: "Acme Lending",
    service: "encompass",
    env: "production",
    status: "degraded",
    lastCheckAt: "2026-05-13T11:35:00Z",
    latencyMs: 2140,
  },
  {
    tenantId: "tnt_acme",
    tenantName: "Acme Lending",
    service: "anthropic",
    env: "production",
    status: "ok",
    lastCheckAt: "2026-05-13T11:36:00Z",
    latencyMs: 388,
  },
  {
    tenantId: "tnt_summit",
    tenantName: "Summit Mortgage",
    service: "encompass",
    env: "production",
    status: "ok",
    lastCheckAt: "2026-05-13T11:32:00Z",
    latencyMs: 612,
  },
  {
    tenantId: "tnt_summit",
    tenantName: "Summit Mortgage",
    service: "slack",
    env: "production",
    status: "ok",
    lastCheckAt: "2026-05-13T11:36:00Z",
    latencyMs: 132,
  },
  {
    tenantId: "tnt_northstar",
    tenantName: "Northstar Home Loans",
    service: "encompass",
    env: "production",
    status: "ok",
    lastCheckAt: "2026-05-13T11:30:00Z",
    latencyMs: 720,
  },
  {
    tenantId: "tnt_bridgeway",
    tenantName: "Bridgeway Capital",
    service: "encompass",
    env: "sandbox",
    status: "ok",
    lastCheckAt: "2026-05-13T11:28:00Z",
    latencyMs: 480,
  },
  {
    tenantId: "tnt_bridgeway",
    tenantName: "Bridgeway Capital",
    service: "email",
    env: "sandbox",
    status: "not_connected",
    lastCheckAt: "2026-05-13T11:28:00Z",
  },
  {
    tenantId: "tnt_meridian",
    tenantName: "Meridian Funding",
    service: "encompass",
    env: "production",
    status: "down",
    lastCheckAt: "2026-05-13T11:00:00Z",
  },
];

export const SAMPLE_PLATFORM_WORKFLOWS: PlatformWorkflow[] = [
  {
    id: "tpo-submission-triage",
    tenantId: "tnt_acme",
    tenantName: "Acme Lending",
    name: "TPO submission triage",
    status: "live",
    env: "production",
    runs24h: 412,
    successRate: 0.97,
    lastRunAt: "2026-05-13T07:42:00Z",
  },
  {
    id: "condition-extraction",
    tenantId: "tnt_acme",
    tenantName: "Acme Lending",
    name: "Condition extraction from disclosed docs",
    status: "live",
    env: "production",
    runs24h: 1284,
    successRate: 0.92,
    lastRunAt: "2026-05-13T08:11:00Z",
  },
  {
    id: "trailing-docs",
    tenantId: "tnt_acme",
    tenantName: "Acme Lending",
    name: "Post-close trailing doc pursuit",
    status: "live",
    env: "production",
    runs24h: 612,
    successRate: 0.99,
    lastRunAt: "2026-05-13T11:00:00Z",
  },
  {
    id: "summit-triage",
    tenantId: "tnt_summit",
    tenantName: "Summit Mortgage",
    name: "Wholesale submission triage",
    status: "live",
    env: "production",
    runs24h: 380,
    successRate: 0.94,
    lastRunAt: "2026-05-13T11:20:00Z",
  },
  {
    id: "summit-conditions",
    tenantId: "tnt_summit",
    tenantName: "Summit Mortgage",
    name: "Condition reconciliation",
    status: "live",
    env: "production",
    runs24h: 232,
    successRate: 0.91,
    lastRunAt: "2026-05-13T11:18:00Z",
  },
  {
    id: "northstar-svc",
    tenantId: "tnt_northstar",
    tenantName: "Northstar Home Loans",
    name: "Service SLA babysitter",
    status: "paused",
    env: "production",
    runs24h: 0,
    successRate: 0.86,
    lastRunAt: "2026-05-12T20:00:00Z",
  },
  {
    id: "bridgeway-pilot",
    tenantId: "tnt_bridgeway",
    tenantName: "Bridgeway Capital",
    name: "Doc OCR pilot",
    status: "draft",
    env: "sandbox",
    runs24h: 14,
    successRate: 0.78,
    lastRunAt: "2026-05-13T10:14:00Z",
  },
];
